### ISSUE TITLE
Questions about the Training Dataset

### ISSUE THREAD

**Issue by sp9103** [YoungSean/NIDS-Net#3]
First of all, thank you for sharing your excellent experimental results and code. I have a question regarding the training dataset.

Did you use the YCBV and LMO datasets when training the results that you posted on the BOP Challenge Leaderboard?

If so, I am confused about whether this can be considered unseen object segmentation.

**Comment by YoungSean** [comment]
The adapters are only trained with instance embeddings from template images.

Detection datasets include YCBV and LMO from VoxDet. We trained only their instance embeddings for adapters separately. Only template images are available, whereas we could not train on query images. We do not use them for segmentation.

For YCBV and LMO of the BOP 2023 segmentation tasks, we trained a common adapter with all template instance embeddings of seven datasets in [this script](https://github.com/YoungSean/NIDS-Net/blob/main/obj_adapter.py). 

[CNOS](https://github.com/nv-nguyen/cnos) used the term "novel object segmentation". In recent papers like [VoxDet](https://github.com/Jaraxxus-Me/VoxDet) and [InsDet](https://github.com/insdet/instance-detection), they are trying to differentiate object and instance since this task is looking for the exact **instances**.
